[platformio]
default_envs = tiger-camera-v1

[env:tiger-camera-v1]
platform = espressif32 @ 7.0.1
board = goouuu-esp32-s3-cam-n16r8
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
  adafruit/Adafruit GFX Library @ ^1.12.6
  adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0
  bodmer/TJpg_Decoder @ ^1.1.0
